apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: movie-watchlist
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jawna10/movie-watchlist-gitops.git
    targetRevision: main
    path: helm/movie-watchlist
    helm:
      releaseName: movie-watchlist
      valueFiles:
        - ../../environments/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: movie-watchlist
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m