apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebeat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: filebeat
    targetRevision: 7.17.3
    helm:
      values: |
        daemonset:
          enabled: true
        
        filebeatConfig:
          filebeat.yml: |
            filebeat.inputs:
            - type: container
              paths:
                - /var/log/containers/*.log
              processors:
              - add_kubernetes_metadata:
                  host: ${NODE_NAME}
                  matchers:
                  - logs_path:
                      logs_path: "/var/log/containers/"
            
            output.elasticsearch:
              host: '${NODE_NAME}'
              hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master.logging.svc.cluster.local:9200}'
        
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 400Mi
  
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true